// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJgAUUYoVlJr3THDkwx8TjUfQ6wptqz8',
    appId: '1:272139979658:web:c1ca25a1226d8f9d8b1673',
    messagingSenderId: '272139979658',
    projectId: 'flutterproject-6372e',
    authDomain: 'flutterproject-6372e.firebaseapp.com',
    storageBucket: 'flutterproject-6372e.appspot.com',
    measurementId: 'G-5J0KDZ235V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPDyayV18VINhMfN0FHjfjVoUJ3yZqvU',
    appId: '1:272139979658:android:d55d49ae04fdf9358b1673',
    messagingSenderId: '272139979658',
    projectId: 'flutterproject-6372e',
    storageBucket: 'flutterproject-6372e.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcEHrC8ZmZQlIRhKg9dowobfBukTrIPuE',
    appId: '1:272139979658:ios:823d578e329b7c8a8b1673',
    messagingSenderId: '272139979658',
    projectId: 'flutterproject-6372e',
    storageBucket: 'flutterproject-6372e.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcEHrC8ZmZQlIRhKg9dowobfBukTrIPuE',
    appId: '1:272139979658:ios:823d578e329b7c8a8b1673',
    messagingSenderId: '272139979658',
    projectId: 'flutterproject-6372e',
    storageBucket: 'flutterproject-6372e.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwJgAUUYoVlJr3THDkwx8TjUfQ6wptqz8',
    appId: '1:272139979658:web:63e4ae431ea174ec8b1673',
    messagingSenderId: '272139979658',
    projectId: 'flutterproject-6372e',
    authDomain: 'flutterproject-6372e.firebaseapp.com',
    storageBucket: 'flutterproject-6372e.appspot.com',
    measurementId: 'G-RS53GWJ82G',
  );

}